name: validation

on:
  pull_request:
    branches:
      - main
  # scheduled validation won't work if datapackage includes number of rows
  # is running it regularly useful to alert to changes in structure?
  # schedule:
  #  schedule: # run automatically on main branch each Tuesday at 11am
  #   - cron: "0 16 * * 2"


jobs:

  # Validate
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Validate data
        uses: frictionlessdata/frictionless-ci@v2
        with:
          packages: "pgp_datapackage.json"
